baseURL = 'https://altbound.com/'
languageCode = 'en-us'
title = 'altbound'
theme = 'altbound-theme'
canonifyURLs = true
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

# Force HTTPS
[security]
  [security.http]
    forceHttps = true

[params]
  description = "where outbound meets inbound, differently"
  
[params.colors]
  primary = "#00adb5"
  primaryLight = "#00dee8"
  background = "#111111"
  text = "#eeeeee"
  lightGray = "#222222"
  mediumGray = "#333333"

[menu]
  [[menu.main]]
    name = "Secrets"
    url = "https://alex.altbound.com/"
    weight = 1
    [menu.main.params]
      target = "_blank"
  [[menu.main]]
    name = "Founder"
    url = "https://www.linkedin.com/in/alex-loughlin-b49a9b110/"
    weight = 2
    [menu.main.params]
      target = "_blank"
  [[menu.main]]
    name = "Book a Call"
    url = "https://calendly.com/alex-if7j/discovery"
    weight = 3
    [menu.main.params]
      target = "_blank"
      class = "cta-button"
