baseURL = 'https://altbound.com/'
languageCode = 'en-us'
title = 'altbound'
theme = 'altbound-theme'
canonifyURLs = true
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

# Force HTTPS
[security]
  [security.http]
    forceHttps = true

[params]
  description = "Done-for-you inbound + outbound for B2B growth. Book sales meetings that convert through email, LinkedIn and social selling."
  author = "Alex Loughlin"
  images = ["images/og-image.jpg"]
  showPricing = false
  
[params.seo]
  # Site verification codes
  googleSiteVerification = "" # Add your Google verification code if you have one
  
[params.social]
  linkedin = "https://www.linkedin.com/in/alex-loughlin-b49a9b110/"

[params.colors]
  primary = "#00adb5"
  primaryLight = "#00dee8"
  background = "#111111"
  text = "#eeeeee"
  lightGray = "#222222"
  mediumGray = "#333333"

[menu]
  [[menu.main]]
    name = "Secrets"
    url = "https://alex.altbound.com/"
    weight = 1
    [menu.main.params]
      target = "_blank"
  [[menu.main]]
    name = "Founder"
    url = "https://www.linkedin.com/in/alex-loughlin-b49a9b110/"
    weight = 2
    [menu.main.params]
      target = "_blank"
  [[menu.main]]
    name = "Book a Call"
    url = "https://cal.com/alex-altbound/30min"
    weight = 3
    [menu.main.params]
      target = "_blank"
      class = "cta-button"
