baseURL = 'https://altbound.com/'
languageCode = 'en-us'
title = 'altbound'
theme = 'altbound-theme'

[params]
  description = "where outbound meets inbound, differently"
  
[params.colors]
  primary = "#00adb5"
  primaryLight = "#00dee8"
  background = "#111111"
  text = "#eeeeee"
  lightGray = "#222222"
  mediumGray = "#333333"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Services"
    url = "/services/"
    weight = 2
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 3
